## application.yml para microservicio scotiabank-challenge
server:
  port: 8088

spring:
  application:
    name: be-scotiabank-challenge-v1
  datasource:
    ##url: jdbc:h2:file:./data/colegio-db   # ruta relativa al directorio donde se ejecuta la app
    url: jdbc:h2:mem:colegio
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false
  jpa:
    hibernate:
      ddl-auto: update    # para que Hibernate actualice el esquema sin borrar datos
    show-sql: true        # opcional, para ver las consultas SQL en consola
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true